### ISSUE TITLE
Скачивание через youtube-dl

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/Cosplay2-Downloader#9]
Можно подключить youtube-dl и скачивать с Youtube и некоторых файлообменников типа Google Drive.

Единственная проблема: утилита называет файлы по названию видео и ставит mp4 низко по приоритетам, т.е. можно спокойно скачать файл «BLACKPINK - ‘뚜두뚜두 (DDU-DU DDU-DU)’ M/V.webm»

**Comment by Himura2la** [comment]
Ну, переименовать то всегда можно, а вот низкое качество это реальный шоустопер. А оно умеет с яндекс диском и мэйлом? Если да, то даже без ютюба имеет смысл, ибо мы требуем строго облака

**Comment by Oreolek** [comment]
Мейл вроде умеет, а яндекс.диск пока нет. Но когда-нибудь кто-нибудь напишет плагин… в общем, это логичнее чем писать сотню своих парсеров.

mp4 это не низкое качество, просто Youtube хранит всё выше 720p в других форматах: webm, av1 и т.д. MPEG как кодек очень устарел.
